# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 20:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('utilitarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField()),
                ('ofline', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=40)),
                ('tiempo_tolerancia', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=5)),
                ('longitud', models.IntegerField()),
                ('latitud', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventoProgramado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Evento')),
            ],
            options={
                'verbose_name': 'Evento programado',
                'verbose_name_plural': 'Eventos programados',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envio', models.CharField(max_length=10)),
                ('numero_recepcion', models.CharField(max_length=10)),
                ('mensaje_entregado', models.CharField(max_length=60)),
                ('tipo_mensaje', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='PlanMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(max_length=10)),
                ('mensaje_previo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Plan mensaje',
                'verbose_name_plural': 'Plan mensaje',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Periodo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.Persona'),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Periodo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='evento_programado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EventoProgramado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Matricula'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
