# Generated by Django 2.1.3 on 2018-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('principal', '0002_remove_asistencia_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='ofline',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
