# Generated by Django 2.1.3 on 2018-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utilitarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
