# Generated by Django 2.1.3 on 2018-11-28 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utilitarios', '0003_persona_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='dnicodigo',
            new_name='dni',
        ),
    ]
